# A medium standard (one public subnet) network configuration
subnets: [1, 1, 3, 3, 3]
topology: [[ 1, 1, 1, 1, 0, 0],
           [ 0, 1, 1, 1, 0, 0],
           [ 0, 1, 1, 1, 1, 0],
           [ 0, 0, 0, 1, 1, 1],
           [ 0, 0, 0, 0, 1, 1]]
services: 3
sensitive_machines: [[1, 0, 1000],
                     [2, 0, 1000],
                     [4, 2, 1000]]
