# A network with a single subnet that has one vulnerable machine that must be compromised
# to access other machines behind firewall
subnets: [16]
topology: [[ 1, 1]],
           [ 1, 1]]
sensitive_machines: [[1, 3, 10],
                     [1, 8, 10]]
num_services: 5
service_exploits:
  ftp:
    - 0.7
    - 1
  ssh:
    - 0.7
    - 1
  http:
    - 0.7
    - 1
  samba:
    - 0.7
    - 1
  smtp:
    - 0.7
    - 1
machine_configurations:
  (1, 0): [ftp]
  (1, 1): [ftp, ssh]
  (1, 2): [ftp]
  (1, 3): [ftp]
  (1, 4): [ftp]
  (1, 5): [http]
  (1, 6): [ftp]
  (1, 7): [ftp, ssh]
  (1, 8): [samba]
  (1, 9): [ftp]
  (1, 9): [smtp]
firewall:
  (0, 1): [http]
  (1, 0): []
