# A smallish standard (one public subnet) network configuration
subnets: [1, 1, 3]
topology: [[ 1, 1, 1, 1],
           [ 0, 1, 1, 1],
           [ 0, 1, 1, 1]]
services: 3
sensitive_machines: [[1, 0, 9000],
                     [2, 2, 5000]]
