subnets: [1, 3, 4, 3, 3]
subnet_connections: [[ 1, 1, 1, 1, 0, 0],
                    [ 0, 1, 1, 1, 0, 0],
                    [ 0, 1, 1, 1, 1, 0],
                    [ 0, 0, 0, 1, 1, 1],
                    [ 1, 0, 0, 0, 1, 1]]
services: 5
sensitive_machines: [(2, 2, 1000), (3, 0, 500), (3, 1, 500)]
